# Site settings
title: Robert Lawrence Smith
description: "Bio, Blog, and Personal Projects"
url: "https://robert-lawrence.me"




# Secondary Parameters
baseurl: ""
header-img: img/circles.jpg
headercolor: "#FFFFFF"
# logo: /project-pages/img/logos/Project-Pages-New-Logo-Inverted.png

# Tertiary Parameters
github_username:  rob2001
project_repository: project-pages
disqus_shortname: project-pages

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "css/theme/README.md"]

# Jekyll Settings

defaults:
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      header-img: "img/circles.jpg"

