# Site settings
title: Portfolio
description: "The Personal Projects of Robert Smith"
url: "https://rob2001.github.io"




# Secondary Parameters
baseurl: "/project-pages"
header-img: img/home-bg.jpg
headercolor: "#FFFFFF"
logo: /project-pages/img/logos/Project-Pages-New-Logo-Inverted.png

# Tertiary Parameters
github_username:  rob2001
project_repository: project-pages
disqus_shortname: project-pages
g-analytics: UA-75881392-1
altmetric: false

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "css/theme/README.md]

# Jekyll Settings

defaults:
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      header-img: "img/home-bg.jpg"

